name: Tagged releases

on:
  push:
    tags:
      - 'v*'

jobs:
  release-github:
    name: Create GitHub release
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    environment: foss-production
    steps:
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
        run: |
          TMP_KEYSTORE_DIR_PATH="${RUNNER_TEMP}"/keystore
          mkdir -p "${TMP_KEYSTORE_DIR_PATH}"
          TMP_KEYSTORE_FILE_PATH="${TMP_KEYSTORE_DIR_PATH}"/keystore.jks
          echo $ENCODED_KEYSTORE | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"
          echo "STORE_PATH=$(echo $TMP_KEYSTORE_FILE_PATH)" >> $GITHUB_ENV

      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: Setup project and build environment
        uses: ./.github/actions/common-setup

      - name: Get the version
        id: tagger
        uses: jimschubert/query-tag-action@0b288a5fff630fea2e96d61b99047ed823ca19dc #v2.2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD

      - name: Assemble beta APK
        if: contains(steps.tagger.outputs.tag, '-beta')
        run: ./gradlew assembleFossBeta
        env:
          VERSION: ${{ github.ref }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Assemble production APK
        if: "!contains(steps.tagger.outputs.tag, '-beta')"
        run: ./gradlew assembleFossRelease
        env:
          VERSION: ${{ github.ref }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create pre-release
        if: contains(steps.tagger.outputs.tag, '-beta')
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda #v2.2.1
        with:
          prerelease: true
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: ${{ steps.tagger.outputs.tag }}
          generate_release_notes: true
          files: app/build/outputs/apk/foss/beta/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: "!contains(steps.tagger.outputs.tag, '-beta')"
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda #v2.2.1
        with:
          prerelease: false
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: ${{ steps.tagger.outputs.tag }}
          generate_release_notes: true
          files: app/build/outputs/apk/foss/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-gplay:
    name: Create Google Play release
    runs-on: ubuntu-22.04
    environment: gplay-production
    steps:
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
        run: |
          TMP_KEYSTORE_DIR_PATH="${RUNNER_TEMP}"/keystore
          mkdir -p "${TMP_KEYSTORE_DIR_PATH}"
          TMP_KEYSTORE_FILE_PATH="${TMP_KEYSTORE_DIR_PATH}"/keystore.jks
          echo $ENCODED_KEYSTORE | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"
          echo "STORE_PATH=$(echo $TMP_KEYSTORE_FILE_PATH)" >> $GITHUB_ENV

      - name: Decode Google Play service account key
        env:
          ENCODED_SERVICE_KEY: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON_BASE64 }}
        run: |
          TMP_SERVICEKEY_DIR="${RUNNER_TEMP}"/gplaykey
          mkdir -p "${TMP_SERVICEKEY_DIR}"
          TMP_SERVICEKEY_FILE_PATH="${TMP_SERVICEKEY_DIR}"/service_account.json
          echo $ENCODED_SERVICE_KEY | base64 -di > "${TMP_SERVICEKEY_FILE_PATH}"
          echo "SUPPLY_JSON_KEY=$(echo $TMP_SERVICEKEY_FILE_PATH)" >> $GITHUB_ENV

      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: Setup project and build environment
        uses: ./.github/actions/common-setup

      - name: Get the version
        id: tagger
        uses: jimschubert/query-tag-action@0b288a5fff630fea2e96d61b99047ed823ca19dc #v2.2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD

      - name: Set up ruby env
        uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 #v1.229.0
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Assemble beta and upload to Google Play
        if: contains(steps.tagger.outputs.tag, '-beta')
        run: bundle exec fastlane beta
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Assemble production and upload to Google Play
        if: "!contains(steps.tagger.outputs.tag, '-beta')"
        run: bundle exec fastlane production
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}